[package]
name = "browser"
version = "0.1.6"
authors = ["flekystyley <flekystyley@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
